### ISSUE TITLE
Problem with MS-CleanR peak filtering in MS Dial version5

### ISSUE THREAD

**Issue by carouger** [systemsomicslab/MsdialWorkbench#121]
Dear all,
I am trying to use the last version of MS Dial (vers. 5.1.230517) but once I come to the MS-CleanR peak filtering step, when I click on Apply after putting the different parameters (blank ratio, incorrect mass, RDS, RMD), nothing happens.
Can you please help me?
Thank you!

**Comment by kozo2** [comment]
Hi @carouger 

It happens by checking or unchecking a checkbox hidden in the Peak Spot Navigator
(after clicking the "Apply" button) to show or hide the peaks.

You can see it in this YouTube video
https://youtu.be/c-_mP8A9I04?t=105

If it still doesn't work, feel free to comment again!
