### ISSUE TITLE
Reference for demo data

### ISSUE THREAD

**Issue by Soumya624** [systemsomicslab/MsdialWorkbench#128]
Hi,

Is there any dummy .wiff available for testing? I am using the current version of MS-Dial. But, couldn't find any demo folder for mass spectrometry data. Any link/reference of the archive in the README.md would be highly helpful!

Thanks!

**Comment by kozo2** [comment]
Hi @Soumya624 
Sorry for the late reply.

>  Is there any dummy .wiff available for testing?

We don't have a dummy .wiff, but we do have demo .wiff files for testing.
http://prime.psc.riken.jp/compms/msdial/main.html#:~:text=CCS%20database).-,Demonstration%20files,-Lipid%20profiling%20of

> But, couldn't find any demo folder for mass spectrometry data.

Sorry, but I don't think we will be adding demo files to reduce the data size of our releases.
We will be doing future releases in GitHub releases.
GitHub releases has a 2GB limit on file size.

> Any link/reference of the archive in the README.md would be highly helpful!

Thanks for the comment.
I will do it.

**Comment by Soumya624** [comment]
Hi @kozo2 ,

Thanks a lot for the link. It's working fine from my end!
