### ISSUE TITLE
Problem with export normalised data using version 5

### ISSUE THREAD

**Issue by FunkiiL** [systemsomicslab/MsdialWorkbench#139]
Dear all,
When I export normalised data from MS-DIAL, the output .csv file often appear in a confused format.

When I export normalised Area data, for a sample, each cell of the corresponding column should represent the lc-ms area corresponding to a substance of it, but in the data I exported, other sample names, FALSE, -1, data with ':' and so on are often appeared in the column, which is strange. A simple example is shown below. 

 average RT            average MZ                  sample1                                 sample2 
    8.879                   335.04319          80485.7791564993             92384.1259323545
   25.266                   112.986              6907.01276694368                           -1
    2.023                  244.96782                   A6.22.3.1                        28173.6231583602
   12.165                  282.06686                    FALSE                             6.817:1000.39108
 
What is the reason for these confusing formats? Can you please help me?
Thank you very much!

**Comment by kozo2** [comment]
Hi @FunkiiL , Thank you for your feedback.
> When I export normalised data from MS-DIAL, the output .csv file often appear in a confused format.

By the way, would it also be a confused format if you select `txt` in the `Export format:` pull down menu? (That information will help us.)

> average RT average MZ sample1 sample2
> 8.879 335.04319 80485.7791564993 92384.1259323545
> 25.266 112.986 6907.01276694368 -1
> 2.023 244.96782 A6.22.3.1 28173.6231583602
> 12.165 282.06686 FALSE 6.817:1000.39108

Can you reply a comment with a screenshot of this actual screen,
even if it is only part of it?
Just a part of it is fine.

In addition, can you give us the full version number of version 5?

**Comment by FunkiiL** [comment]
Dear @kozo2, thanks for your reply!
An example format of .csv file is shown as the picture. The full version number of MS-DIAL I used is 5.1.230222.

![WechatIMG147](https://github.com/systemsomicslab/MsdialWorkbench/assets/136693636/96d965f4-8e93-4313-94c4-545bf18f8a4b)

When I export the normalised data with .txt, it looks more chaotic than .csv format.

<img width="734" alt="image" src="https://github.com/systemsomicslab/MsdialWorkbench/assets/136693636/fd67e144-9212-4377-a680-614305c00b13">

Looking forward to your reply! Thank you very much!

**Comment by YukiMatsuzawa** [comment]
Hi @FunkiiL,

I checked your table data, and it seems that there's a missing column between "Metabolite name" and "Spectrum reference". Did you delete those columns? If you did, could you please confirm whether the values in those columns for AlignmentID 940 are correct or not?

**Comment by FunkiiL** [comment]
Hi @YukiMatsuzawa,
Thanks for your reply!
Columns between "Metabolite name" and "Spectrum reference" were hidden by me since I wanted to show the content of samples last time. For the line of AlignmentID 940 as an example, I think it gets confused starting with "Adduct type" because the table automatically breaks down the name of the substance into several columns. Is there any way to solve this problem?

<img width="1245" alt="image" src="https://github.com/systemsomicslab/MsdialWorkbench/assets/136693636/2697e901-d7a5-4da9-b7ae-0bfbd763d06e">

Thank you very much!

**Comment by YukiMatsuzawa** [comment]
I apologize for the bug in the CSV output. I will fix it immediately. In the meantime, please export the data as a tsv file (.txt) and open it in Excel by dragging and dropping the tsv file into Excel. Excel should be able to read the contents of the tsv file correctly.

**Comment by FunkiiL** [comment]
I have tried to open the .txt in Excel, and it works! Thank you very much!
Have a nice day :)
