### ISSUE TITLE
Propper GNPS export forr FBMN in MS-DIAL 5

### ISSUE THREAD

**Issue by mukhomorr** [systemsomicslab/MsdialWorkbench#303]
Hello! I'd like to know, i there is option for alignment results export for FBMN pipeline in GNPS, as there is was such option in older versions?

**Comment by YukiMatsuzawa** [comment]
Hello and thank you for your inquiry! We're indeed planning to develop features similar to those in the older versions, including the alignment results export for the FBMN pipeline in GNPS. However, these features aren't available yet in the current version. We apologize for any inconvenience this may cause and appreciate your understanding as we work on bringing these updates to you.
