### ISSUE TITLE
extracting feature list created from ms/ms fragment ion searcher 

### ISSUE THREAD

**Issue by shota-matsumura** [systemsomicslab/MsdialWorkbench#319]
Hi, 

I was wondering if there is a way to export just the MS features contained within a given ms/ms fragment search? If not, is there an alternative approach within the msdial software by which i can mark the compounds found within the ms/ms fragment search prior to exporting the feature list? 

I am currently using msdial v 5.1 .23

Thank you,

Warm regards,

Shota.

**Comment by shota-matsumura** [comment]
Also, 

Thanks in advance for providing such a great open source platform to the MS community!

**Comment by YukiMatsuzawa** [comment]
I apologize for the delayed response.

In MSDIAL, when exporting peak spotting results, you can use the current filtering parameters to narrow down the peaks that will be exported. The way to do this is by applying your filters in the main view or table view, then proceed to Export and check the 'Filtering by current parameter' option before executing the export. However, please note that this feature is currently available only after performing Alignment.

I hope this helps with your query.

<img width="557" alt="image" src="https://github.com/systemsomicslab/MsdialWorkbench/assets/122433968/67e0cbd9-1d01-4251-872b-b15c8e907f62">
