### ISSUE TITLE
autoflashback/shutdown

### ISSUE THREAD

**Issue by wzhang15** [systemsomicslab/MsdialWorkbench#321]
I'm using the version 4.9.
after the whole processing of around 30 samples,
When I click "compound search" to check the identity is correct or not, the software just shutdown immediatrly. It's so frequent that I can not do anything.
![pic](https://github.com/systemsomicslab/MsdialWorkbench/assets/133013942/acdd053f-9395-4d78-a542-d4c3a6d3f40f)

Another problem is I cannot open the alignment table.
![pic1 ](https://github.com/systemsomicslab/MsdialWorkbench/assets/133013942/cf018d2e-7573-4c1e-bb1c-273ede5a8681)

Many thanks for helping.

**Comment by Bujee415** [comment]
Hello!
Sorry for the late reply!
Did you solve this problem? WI highly recommend retrying it with the newest version.
Thanks!
