### ISSUE TITLE
 There are only 25 records in PFAS database

### ISSUE THREAD

**Issue by PulaFrank** [systemsomicslab/MsdialWorkbench#351]
There are only 25 records in PFAS database (show 6936 records in ms-dial web page) in .db format when we convert the PFAS data base in .msp to that in .db format by mzVault.
Besides, PFAS database is only 3.3Mb after downloading. I suspect that this database for PFAS is lack of MS2 spectra information.
![GRW-MS2](https://github.com/systemsomicslab/MsdialWorkbench/assets/146656784/350cdab3-57b4-453f-8f8f-6b2b629c002b)

**Comment by kozo2** [comment]
I believe your point is based on mzVault.
Therefore, We cannot help you with this issue. Sorry.
