### ISSUE TITLE
Tutorial page link 404's

### ISSUE THREAD

**Issue by Steph-Buck** [systemsomicslab/MsdialWorkbench#352]
The link to the tutorial page on the [read me](https://github.com/systemsomicslab/MsdialWorkbench?tab=readme-ov-file) 404's

![Screenshot 2024-04-30 103201](https://github.com/systemsomicslab/MsdialWorkbench/assets/168580407/01faa4d2-1b2e-4ecd-a69e-e6111620ae88)
![Screenshot 2024-04-30 103341](https://github.com/systemsomicslab/MsdialWorkbench/assets/168580407/bc972b0e-6770-46b9-8497-b39bd6257cc2)

**Comment by kozo2** [comment]
@Steph-Buck 
Thank you for your issue 🙏 
I fixed the link at https://github.com/systemsomicslab/MsdialWorkbench/commit/8baa8d45880e3add8be4ae058e6afbceaf193716
