### ISSUE TITLE
Curation peak picker has RT x-axis instead of m/z for direct infusion

### ISSUE THREAD

**Issue by Massmz** [systemsomicslab/MsdialWorkbench#370]
I am using the Direct Infusion separation type and Profile MS1 data type for flow injection data. I noticed that the manual peak curation window has the x-axis labeled as retention time rather than m/z.
![image](https://github.com/systemsomicslab/MsdialWorkbench/assets/168754922/a379c12e-7762-496f-bb88-38236be55265)

**Comment by Bujee415** [comment]
Hello!
Sorry for the late reply!
Thank you for letting us know! We will check on it!
Thanks!
