### ISSUE TITLE
Tutorial link

### ISSUE THREAD

**Issue by valen320** [systemsomicslab/MsdialWorkbench#376]
Hi!
There is an error in the link to tutorial:
https://github.com/systemsomicslab/MsdialWorkbench/tree/MSFINDER-v3.61?tab=readme-ov-file#usage

See the tutorial page: https://mtbinfo-team.github.io/mtbinfo.github.io/
That link leads to 404.

The correct link is:
https://systemsomicslab.github.io/mtbinfo.github.io/MS-FINDER/tutorial

Please update info

**Comment by Bujee415** [comment]
Thank you for your kindness. We updated the info!
Have a great day!
