### ISSUE TITLE
Unable to normalise GCMS data in MSDIAL5

### ISSUE THREAD

**Issue by ajburx** [systemsomicslab/MsdialWorkbench#385]
Hello,

I have an issue following processing GCMS data in MSDIAL v5.3.240719 where LOWESS normalisation is greyed out (analytical order has been inputted in file property menu and QC sample type has been correctly set). Is this feature unsupported in MSDIAL v5?

There is another issue where I am unable to use a custom library for peak annotation (please see issue #374 opened by another user)

Thank you for your help and development of this program

**Comment by Bujee415** [comment]
Hello!
Sorry for the late reply!
Did you solve this problem? If not, I highly suggest retrying with the newest version!
Thanks!
