### ISSUE TITLE
Related ions feature in the alignment spot viewer in MS-DIAL 5?

### ISSUE THREAD

**Issue by villekoi** [systemsomicslab/MsdialWorkbench#406]
Hello,

We have been wondering if the feature that connects related aligned peaks (e.g., adducts, in-source fragments, correlating ions) is coming to MS-DIAL 5. It's one of the best features in MS-DIAL because it literally helps connecting the dots in the data and has often prevented misannotations.

Kind regards,
Ville Koistinen

![image](https://github.com/user-attachments/assets/8cd193b5-c982-4429-a078-0b1fee6a7095)

**Comment by Bujee415** [comment]
Hi, Ville!
This feature is now on MS-DIAL 5 if you didn't know. It's nice to hear some feedback!
Hope you doing well with MS-DIAL!
