### ISSUE TITLE
Issues with csv export of alignment results in MS-DIAL 5

### ISSUE THREAD

**Issue by daehwankim12** [systemsomicslab/MsdialWorkbench#417]
Hello,

I've recently encountered an issue while working with MS-DIAL 5. After preprocessing my data and exporting the alignment results to a csv file, I noticed that some of the annotated compound names are split across multiple cells when opening the file in Excel.

Upon investigating the msp library, which I used during the preprocessing step, I found that some compound names containing commas are enclosed in quotation marks. If a "NAME" field in the msp library already contains both quotation marks and a comma, the export process seems to add additional quotation marks. This causes Excel to misinterpret the field as unquoted, leading to the compound name being incorrectly split across multiple cells.

Could you please look into this issue and provide any guidance on how to resolve it?

Thank you for your time and consideration.

**Comment by Bujee415** [comment]
Hello!
Sorry for the late reply!
I am happy to say that we fixed this recently just like you said.
I appreciate your cooperation!
