### ISSUE TITLE
MSDIAL 4.9.221218 misses the IBF conversion executable

### ISSUE THREAD

**Issue by eeko-kon** [systemsomicslab/MsdialWorkbench#419]
https://zenodo.org/records/12589462

This version is missing the IBF conversion executable - or am I missing something?

Thank you!

**Comment by kozo2** [comment]
The ibf converter is no longer supported in ms-dial team, and you can directly import the ion mobility data files into ms-dial. For example, how to import .d folder of Bruker can be browsed here.
https://www.youtube.com/watch?v=jB729eQ6QQ0
https://www.youtube.com/watch?v=RGspcP5OoWo

**Comment by kozo2** [comment]
If you don't mind, I would also appreciate it if you could tell me a little bit about why you need that file format.

**Comment by eeko-kon** [comment]
Ah my bad, thank you!
