### ISSUE TITLE
‘low score' in annotations

### ISSUE THREAD

**Issue by liangzhengjiao** [systemsomicslab/MsdialWorkbench#421]
Hi MS-DIAL Developers,

Thank you for the updates to MS-DIAL!
I encountered several instances of "low score:" in the annotations while using MS-DIAL v5.3.240719.
![20241010163924](https://github.com/user-attachments/assets/5f05c039-d7e7-4618-a944-8f979b51a495)
Could you please clarify what "low score" means? I couldn't find its relation to other properties in the results, such as "Total score."

Thanks in advance!
Best regards
Lian

**Comment by Bujee415** [comment]
Hello, Lian!
Sorry for the late reply!
About the definition, when you create a new project on MS-DIAL, there are a few cut-off values for annotation. And "low score" means a spot which has MS/MS spectrum, but some scores are lower than you set.
