### ISSUE TITLE
parameter file for MSDIAL v5

### ISSUE THREAD

**Issue by liaochenlanruo** [systemsomicslab/MsdialWorkbench#462]
Can the developer supply the example parameter file for MSDIAL v5 console?

Thanks!

**Comment by Bujee415** [comment]
Hello!
Sorry for the late reply! I attached example parameter file and you can use it with LC-MS data! (please add your library path)
Hope it helps!

Bujee

[LCMS_exampleConsoleParameter.txt](https://github.com/user-attachments/files/18178371/LCMS_exampleConsoleParameter.txt)
