### ISSUE TITLE
[Feature Suggestion] Display error log when crashing

### ISSUE THREAD

**Issue by Catosine** [systemsomicslab/MsdialWorkbench#483]
Hello all,

As many issues mentioned, I am also struggling in MSDial sudden crashing problem.

It's very hard to debug with no error logs.

So I was wondering if it is possible to display error log when crashing, or add a pre-analysis data quality check feature so user could foresee whether a piece of data may cause crashing.

Thank you all for your great work!

Catosine :D

**Comment by Bujee415** [comment]
Hello, Catosine!
Thank you for your cooperation!
We are working on this and planning to have it on our next release!
Thanks!
