### ISSUE TITLE
Debugging error even after following the installation guide in Visual Studio

### ISSUE THREAD

**Issue by Soumya624** [systemsomicslab/MsdialWorkbench#63]
![Screenshot 2023-03-24 121504](https://user-images.githubusercontent.com/63846042/227490917-b63f3f9e-b030-47bf-a14d-0843523fa277.png)

**Comment by kozo2** [comment]
@Soumya624 Reloading the project may be an effective solution to that.
You can use the keyboard shortcut Ctrl + Shift + F5 to rebuild and reload all projects in your solution.

You can also reload the project with
1. Open Solution Explorer
2. Right-click on the projects in your image's "Project" column.
3. Select "Reload Project" from the context menu.

I hope that helps! Let me know if the above does not solve the problem.

**Comment by Soumya624** [comment]
Hi @kozo2 ,

Thanks for your response. It's solving the problem.

Also, i was interested in **A commandline application of MS-DIAL** project for this year's GSoC. So, is it still open for application?

Thanks

**Comment by kozo2** [comment]
Yes, it's still open.

1. Write your proposal (there is a template in https://github.com/MZmine-MS-DIAL-GSoC/MZmine-MS-DIAL-GSoC.github.io/discussions/13 ).
2. Submit your proposal in https://summerofcode.withgoogle.com/ .
